// Generated by the Scala Plugin for the Protocol Buffer Compiler.
// Do not edit!
//
// Protofile syntax: PROTO3

package org.seekloud.esheepapi.pb.esapi

@SerialVersionUID(0L)
final case class Boy(
    id: _root_.scala.Int = 0,
    name: _root_.scala.Predef.String = "",
    height: _root_.scala.Float = 0.0f,
    weight: _root_.scala.Float = 0.0f
    ) extends scalapb.GeneratedMessage with scalapb.Message[Boy] with scalapb.lenses.Updatable[Boy] {
    @transient
    private[this] var __serializedSizeCachedValue: _root_.scala.Int = 0
    private[this] def __computeSerializedValue(): _root_.scala.Int = {
      var __size = 0
      
      {
        val __value = id
        if (__value != 0) {
          __size += _root_.com.google.protobuf.CodedOutputStream.computeInt32Size(1, __value)
        }
      };
      
      {
        val __value = name
        if (__value != "") {
          __size += _root_.com.google.protobuf.CodedOutputStream.computeStringSize(2, __value)
        }
      };
      
      {
        val __value = height
        if (__value != 0.0f) {
          __size += _root_.com.google.protobuf.CodedOutputStream.computeFloatSize(3, __value)
        }
      };
      
      {
        val __value = weight
        if (__value != 0.0f) {
          __size += _root_.com.google.protobuf.CodedOutputStream.computeFloatSize(4, __value)
        }
      };
      __size
    }
    final override def serializedSize: _root_.scala.Int = {
      var read = __serializedSizeCachedValue
      if (read == 0) {
        read = __computeSerializedValue()
        __serializedSizeCachedValue = read
      }
      read
    }
    def writeTo(`_output__`: _root_.com.google.protobuf.CodedOutputStream): _root_.scala.Unit = {
      {
        val __v = id
        if (__v != 0) {
          _output__.writeInt32(1, __v)
        }
      };
      {
        val __v = name
        if (__v != "") {
          _output__.writeString(2, __v)
        }
      };
      {
        val __v = height
        if (__v != 0.0f) {
          _output__.writeFloat(3, __v)
        }
      };
      {
        val __v = weight
        if (__v != 0.0f) {
          _output__.writeFloat(4, __v)
        }
      };
    }
    def mergeFrom(`_input__`: _root_.com.google.protobuf.CodedInputStream): org.seekloud.esheepapi.pb.esapi.Boy = {
      var __id = this.id
      var __name = this.name
      var __height = this.height
      var __weight = this.weight
      var _done__ = false
      while (!_done__) {
        val _tag__ = _input__.readTag()
        _tag__ match {
          case 0 => _done__ = true
          case 8 =>
            __id = _input__.readInt32()
          case 18 =>
            __name = _input__.readString()
          case 29 =>
            __height = _input__.readFloat()
          case 37 =>
            __weight = _input__.readFloat()
          case tag => _input__.skipField(tag)
        }
      }
      org.seekloud.esheepapi.pb.esapi.Boy(
          id = __id,
          name = __name,
          height = __height,
          weight = __weight
      )
    }
    def withId(__v: _root_.scala.Int): Boy = copy(id = __v)
    def withName(__v: _root_.scala.Predef.String): Boy = copy(name = __v)
    def withHeight(__v: _root_.scala.Float): Boy = copy(height = __v)
    def withWeight(__v: _root_.scala.Float): Boy = copy(weight = __v)
    def getFieldByNumber(__fieldNumber: _root_.scala.Int): _root_.scala.Any = {
      (__fieldNumber: @_root_.scala.unchecked) match {
        case 1 => {
          val __t = id
          if (__t != 0) __t else null
        }
        case 2 => {
          val __t = name
          if (__t != "") __t else null
        }
        case 3 => {
          val __t = height
          if (__t != 0.0f) __t else null
        }
        case 4 => {
          val __t = weight
          if (__t != 0.0f) __t else null
        }
      }
    }
    def getField(__field: _root_.scalapb.descriptors.FieldDescriptor): _root_.scalapb.descriptors.PValue = {
      _root_.scala.Predef.require(__field.containingMessage eq companion.scalaDescriptor)
      (__field.number: @_root_.scala.unchecked) match {
        case 1 => _root_.scalapb.descriptors.PInt(id)
        case 2 => _root_.scalapb.descriptors.PString(name)
        case 3 => _root_.scalapb.descriptors.PFloat(height)
        case 4 => _root_.scalapb.descriptors.PFloat(weight)
      }
    }
    def toProtoString: _root_.scala.Predef.String = _root_.scalapb.TextFormat.printToUnicodeString(this)
    def companion = org.seekloud.esheepapi.pb.esapi.Boy
}

object Boy extends scalapb.GeneratedMessageCompanion[org.seekloud.esheepapi.pb.esapi.Boy] {
  implicit def messageCompanion: scalapb.GeneratedMessageCompanion[org.seekloud.esheepapi.pb.esapi.Boy] = this
  def fromFieldsMap(__fieldsMap: scala.collection.immutable.Map[_root_.com.google.protobuf.Descriptors.FieldDescriptor, _root_.scala.Any]): org.seekloud.esheepapi.pb.esapi.Boy = {
    _root_.scala.Predef.require(__fieldsMap.keys.forall(_.getContainingType() == javaDescriptor), "FieldDescriptor does not match message type.")
    val __fields = javaDescriptor.getFields
    org.seekloud.esheepapi.pb.esapi.Boy(
      __fieldsMap.getOrElse(__fields.get(0), 0).asInstanceOf[_root_.scala.Int],
      __fieldsMap.getOrElse(__fields.get(1), "").asInstanceOf[_root_.scala.Predef.String],
      __fieldsMap.getOrElse(__fields.get(2), 0.0f).asInstanceOf[_root_.scala.Float],
      __fieldsMap.getOrElse(__fields.get(3), 0.0f).asInstanceOf[_root_.scala.Float]
    )
  }
  implicit def messageReads: _root_.scalapb.descriptors.Reads[org.seekloud.esheepapi.pb.esapi.Boy] = _root_.scalapb.descriptors.Reads{
    case _root_.scalapb.descriptors.PMessage(__fieldsMap) =>
      _root_.scala.Predef.require(__fieldsMap.keys.forall(_.containingMessage == scalaDescriptor), "FieldDescriptor does not match message type.")
      org.seekloud.esheepapi.pb.esapi.Boy(
        __fieldsMap.get(scalaDescriptor.findFieldByNumber(1).get).map(_.as[_root_.scala.Int]).getOrElse(0),
        __fieldsMap.get(scalaDescriptor.findFieldByNumber(2).get).map(_.as[_root_.scala.Predef.String]).getOrElse(""),
        __fieldsMap.get(scalaDescriptor.findFieldByNumber(3).get).map(_.as[_root_.scala.Float]).getOrElse(0.0f),
        __fieldsMap.get(scalaDescriptor.findFieldByNumber(4).get).map(_.as[_root_.scala.Float]).getOrElse(0.0f)
      )
    case _ => throw new RuntimeException("Expected PMessage")
  }
  def javaDescriptor: _root_.com.google.protobuf.Descriptors.Descriptor = EsapiProto.javaDescriptor.getMessageTypes.get(1)
  def scalaDescriptor: _root_.scalapb.descriptors.Descriptor = EsapiProto.scalaDescriptor.messages(1)
  def messageCompanionForFieldNumber(__number: _root_.scala.Int): _root_.scalapb.GeneratedMessageCompanion[_] = throw new MatchError(__number)
  lazy val nestedMessagesCompanions: Seq[_root_.scalapb.GeneratedMessageCompanion[_]] = Seq.empty
  def enumCompanionForFieldNumber(__fieldNumber: _root_.scala.Int): _root_.scalapb.GeneratedEnumCompanion[_] = throw new MatchError(__fieldNumber)
  lazy val defaultInstance = org.seekloud.esheepapi.pb.esapi.Boy(
  )
  implicit class BoyLens[UpperPB](_l: _root_.scalapb.lenses.Lens[UpperPB, org.seekloud.esheepapi.pb.esapi.Boy]) extends _root_.scalapb.lenses.ObjectLens[UpperPB, org.seekloud.esheepapi.pb.esapi.Boy](_l) {
    def id: _root_.scalapb.lenses.Lens[UpperPB, _root_.scala.Int] = field(_.id)((c_, f_) => c_.copy(id = f_))
    def name: _root_.scalapb.lenses.Lens[UpperPB, _root_.scala.Predef.String] = field(_.name)((c_, f_) => c_.copy(name = f_))
    def height: _root_.scalapb.lenses.Lens[UpperPB, _root_.scala.Float] = field(_.height)((c_, f_) => c_.copy(height = f_))
    def weight: _root_.scalapb.lenses.Lens[UpperPB, _root_.scala.Float] = field(_.weight)((c_, f_) => c_.copy(weight = f_))
  }
  final val ID_FIELD_NUMBER = 1
  final val NAME_FIELD_NUMBER = 2
  final val HEIGHT_FIELD_NUMBER = 3
  final val WEIGHT_FIELD_NUMBER = 4
}
